name: ml_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python == 3.8.10
  - pandas
  - isort
  - altair
  - altair_viewer
  - altair_saver
  - matplotlib
  - seaborn
  - numpy
  - scikit-learn
  - scipy
  - vega
  - neptune-client
  - joblib
  - pip
  - neptune-optuna
  - imbalanced-learn
  - hyperopt
  - future == 0.13.1
  - pip:
    - git+https://github.com/hyperopt/hyperopt-sklearn.git
  - imbalanced-learn
  - neptune-client