name: ml_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python == 3.8.10
  - pandas
  - matplotlib
  - numpy
  - scikit-learn
  - pip
  - pip:
      - git+https://github.com/hyperopt/hyperopt-sklearn.git
  - imbalanced-learn
  - neptune-client
  - neptune-optuna
  - isort
  - seaborn
  - scipy
  - vega
  - hyperopt
  - imblearn
  - future == 0.13.1
